EmployeeCatalog/MAS.Work.EmployeeCatalog/Controllers/CommentController.cs
namespace MAS.Work.EmployeeCatalog.Controllers {
    #region References
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using System.Threading.Tasks;
    using System.Web;
    using System.Web.Mvc;
    using AutoMapper;
    using MAS.Work.EmployeeCatalog.Helpers;
    using MAS.Work.EmployeeCatalog.Models;
    using MAS.Work.EmployeeCatalog.ViewModels;
    using Microsoft.AspNet.Identity;
    #endregion
    public class CommentController : BaseController {

        [HttpGet]
        public ActionResult GetComments(int? id) {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Logger.Info("{0}: Попытка поиска видео с [id: {1}].", User.Identity.GetUserName(), id.Value);
            Video video = RepManager.Videos.GetById(id.Value);

            if (video == null)
            {
                Logger.Info("{0}: Попытка поиска видео с [id: {1}]: Неудачно.", User.Identity.GetUserName(), id.Value);
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            Logger.Info("{0}: Поиск комментариев для видео [id: {1}]", User.Identity.GetUserName(), id.Value);

            IEnumerable<Comment> comments = RepManager.Comments.GetByPredicate(c => c.LectureId == id.Value);
            Logger.Info("{0}: Поиск комментариев для видео [id: {1}]: Найдено {2} шт.",
                User.Identity.GetUserName(), id.Value, comments.Count());

            var vms = new List<CommentPreviewViewModel>();

            foreach (Comment comment in comments)
            {
                CommentPreviewViewModel vm = Mapper.Map<Comment, CommentPreviewViewModel>(comment);

                vm.Author = RepManager.Employees.GetShortNameByUserId(comment.AuthorId);

                Employee emp = RepManager.Employees.GetByUserId(comment.AuthorId);
                vm.AuthorAvatar = ImageHelper.ConvertByteToBase64(emp.ManInfo.PreviewPhoto ?? GetDefaultPhotoPreview());

                vms.Add(vm);
            }
            Logger.Info(@"{0}: Проведение мэппинга комментариев для просмотра: {1}\{2}",
                User.Identity.GetUserName(), vms.Count, comments.Count());

            return PartialView("_Comments", vms);
        }

        #region Add

        [HttpGet]
        public ActionResult AddComment(int? id) {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Logger.Info("{0}: Попытка поиска видео с [id: {1}].", User.Identity.GetUserName(), id.Value);
            Video video = RepManager.Videos.GetById(id.Value);

            if (video == null)
            {
                Logger.Info("{0}: Попытка поиска видео с [id: {1}]: Неудачно.", User.Identity.GetUserName(), id.Value);
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            Logger.Info("{0}: Попытка поиска видео с [id: {1}]: Найдено 1 вхождение: {2}",
                User.Identity.GetUserName(), id.Value, video.Name);

            var vm = new CommentAddViewModel() { LectureId = id.Value };

            return PartialView("_AddComment", vm);
        }

        [HttpPost]
        public async Task<ActionResult> AddComment(CommentAddViewModel vm) {
            Logger.Info("{0}: Попытка добавления комментария.", User.Identity.GetUserName());
            try
            {
                Comment comment = Mapper.Map<CommentAddViewModel, Comment>(vm);

                var userId = User.Identity.GetUserId();

                comment.Lecture = RepManager.Videos.GetById(vm.LectureId);
                comment.AuthorId = userId;

                RepManager.Comments.Add(comment);

                await RepManager.SaveChangesAsync();
                Logger.Info("{0}: Попытка добавления комментария: Успешно [id: {1}]", User.Identity.GetUserName(), comment.Id);
                return Json(new { Success = true });
            }
            catch (Exception e)
            {
                Logger.Error(e, "{0}: Попытка добавления комментария: Неудачно", User.Identity.GetUserName());
                return Json(new { Success = false, Error = e.Message });
            }
        }

        #endregion

        [HttpPost]
        public async Task<ActionResult> Delete(int? id) {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Comment comment = RepManager.Comments.GetById(id.Value);

            Logger.Info("{0}: Попытка поиска комментария с [id: {1}]", User.Identity.Name, id.Value);

            if (comment == null)
            {
                Logger.Info("{0}: Попытка поиска комментария с [id: {1}]: Неудачно, комментарий не найден", User.Identity.Name, id.Value);

                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            Logger.Info("{0}: Попытка поиска комментария с [id: {1}]: Успешно", User.Identity.Name, id.Value);

            try
            {
                Logger.Info("{0}: Попытка удаления комментария с [id: {1}]", User.Identity.Name, id.Value);

                RepManager.Comments.Delete(comment);
                await RepManager.SaveChangesAsync();

                Logger.Info("{0}: Попытка поиска комментария с [id: {1}]: Успешно", User.Identity.Name, id.Value);
                return Json(new { Success = true });
            }
            catch (Exception e)
            {
                Logger.Error(e, "{0}: Попытка удаления комментария с [id: {1}]: Неудачно", User.Identity.Name, id.Value);
                return Json(new { Success = false, Error = "Произошла ошибка удаления" });
            }
        }
    }
}

EmployeeCatalog/MAS.Work.EmployeeCatalog/Controllers/VideoController.cs
namespace MAS.Work.EmployeeCatalog.Controllers {
    #region References

    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Threading;
    using System.Threading.Tasks;
    using System.Web;
    using System.Web.Configuration;
    using System.Web.Mvc;
    using AutoMapper;
    using Helpers;
    using Microsoft.AspNet.Identity;
    using Models;
    using Validators;
    using ViewModels;
    using FileIO = System.IO.File;
    #endregion

    [Authorize]
    public class VideoController : BaseController {
        /* when implements DI
        private IVideoService _vidService;

        public IVideoService VideoService
        {
            get { return _vidService; }
            set { _vidService = value; }
        }


        public VideoController(IVideoService service)
        {
            VideoService = service;
        }
        */

        [HttpGet]
        public ActionResult Index()
            => View();

        [HttpGet]
        public ActionResult Videos(int? catId, string page) {
            int pageNum = string.IsNullOrEmpty(page) ? 1 : Convert.ToInt32(page);
            int pageSize_ = 15;

            IEnumerable<Video> src;
            // TODO: Организовать получение тех видосов, файлы которых есть
            if (catId.HasValue)
                src = RepManager.Videos.GetByPredicate(vid => vid.CategoryId == catId.Value);
            else
                src = RepManager.Videos.GetByPredicate(vid => vid.IsReady);

            var videos = src
                .OrderByDescending(x => x.UploadingDate)
                .Skip((pageNum - 1) * pageSize_)
                .Take(pageSize_)
                .ToList();

            var pageInfo = new PageInfo {
                PageNumber = pageNum,
                PageSize = pageSize_,
                TotalItems = src.Count()
            };

            var ivm = new PageViewModel<VideoPreviewViewModel> {
                PageInfo = pageInfo,
                Objects = videos.Select((x) => {
                    VideoPreviewViewModel res = Mapper.Map<Video, VideoPreviewViewModel>(x);
                    if (res.Lector != "Не назначен")
                        res.Lector = RepManager.Employees.GetShortName(userName: res.Lector);

                    if (string.IsNullOrEmpty(res.Preview))
                    {
                        var path = WebConfigurationManager.AppSettings["Images:Static:RelativePath"];
                        path = Path.Combine(Server.MapPath(path), "no-preview.png");
                        res.Preview = ImageHelper.GetImageFromFileAsBase64(path);
                    }

                    return res;
                }
                ),
                Param = catId ?? 0,
            };

            return PartialView("_Videos", ivm);
        }

        [HttpGet]
        public ActionResult ViewVideo(int? id) {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Video vid = RepManager.Videos.GetById(id.Value);

            if (vid == null || !FileIO.Exists(vid.Path))
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            /*
            if (!vid.IsConverted || !vid.IsReady)
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden); // or handle somehow
            */

            VideoWatchViewModel vm = Mapper.Map<Video, VideoWatchViewModel>(vid);

            if (vm.Lector != "Не назначен")
                vm.Lector = RepManager.Employees.GetShortName(vm.Lector);

            ViewBag.RelativePath = WebConfigurationManager.AppSettings["Video:RelativePath"].Replace("~", "..");

            return View(vm);
        }

        #region Upload

        [HttpGet]
        [Authorize(Roles = "admin, moder")]
        public ActionResult Upload() {
            var userName = User.Identity.GetUserName();
            var hash = Guid.NewGuid().ToString();

            var configPath = WebConfigurationManager.AppSettings["Video:RelativePath"];

            configPath = Path.Combine(Server.MapPath(configPath), "Temp");

            IActionResultProvider<string> result = CreateTemproryDirectory(configPath, userName, hash);

            if (!result.Succeeded)
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError); // or handle somehow error

            var chunkSize = WebConfigurationManager.AppSettings["VideoUpload:chunkSize"];

            #region Filling viewbag

            // ViewBag.TemporaryPath = result.Result; 
            // возможно реализовать если правильно передавать клиенту без потери структуры строки

            ViewBag.UserName = userName;
            ViewBag.Hash = hash;
            ViewBag.ChunkSize = chunkSize;

            #endregion

            return View("UploadVideo");
        }

        #region Partial uploading (server side)

        [HttpPost]
        [Authorize(Roles = "admin, moder")]
        public ActionResult UploadPartial(HttpPostedFileBase chunk, int chunkNumber, string fileName,
            string userName, string hash) {
            try
            {
                var configPath = WebConfigurationManager.AppSettings["Video:RelativePath"];

                var resultedPath = Server.MapPath(configPath);

                var tempFolder = Path.Combine(resultedPath, "Temp", userName, hash);
                // страшно - лучше бы передавать путь

                var path = Path.Combine(tempFolder, chunkNumber + ".tmp");

                chunk.SaveAs(path);
                return Json(new { Succeeded = true });
            }
            catch (Exception e)
            {
                return Json(new { Succeeded = false, Error = e.Message });
            }
        }

        [HttpPost]
        [Authorize(Roles = "admin, moder")]
        public async Task<ActionResult> UploadComplete(string fileName, int chunksCount,
            string userName, string hash) {
            var configPath = WebConfigurationManager.AppSettings["Video:RelativePath"];

            var resultedPath = Server.MapPath(configPath);

            var tempFolder = Path.Combine(resultedPath, "Temp", userName, hash);

            var dest = Path.Combine(resultedPath, fileName);

            for (int i = 0; i < chunksCount; i++)
            {
                try
                {
                    var path = Path.Combine(tempFolder, i.ToString() + ".tmp");
                    Combine(path, dest);
                }
                catch (Exception)
                {
                    Thread.Sleep(5 * 1000);
                    i--;
                    continue;
                }

            }

            Logger.Info("{0}: Загрузка нового видео [{1}]", userName, fileName);

            #region save video info

            try
            {
                string defaultVideoCatName = WebConfigurationManager.AppSettings["defaults:VideoCategory"],
                       ffmpegTemp = Server.MapPath(WebConfigurationManager.AppSettings["ffmpeg:WorkingPath"]);

                VideoCategory videoCat = RepManager.VideoCategories.GetByPredicateSingle(cat => cat.Name == defaultVideoCatName);
                ApplicationUser user = UserManager.FindByName(userName);

                var video = Video.CreateDefault(dest, user, videoCat);

                using (var ffmpegWorker = FFMpegWorker.Create(ffmpegTemp))
                    video.Duration = ffmpegWorker.GetVideoInfo(video.Path).Duration;

                RepManager.Videos.Add(video);
                await RepManager.SaveChangesAsync();
                await Task.Factory.StartNew(() => CleanUp(userName, Guid.Parse(hash)));

                Logger.Info("{0}: Загрузка нового видео [{1}]: Успешно [id: {2}]", userName, fileName, video.Id);

                return Json(new { Success = true, Id = video.Id });
            }
            catch (Exception e)
            {
                return Json(new { Success = false, Error = e.Message });
            }

            #endregion
        }

        void Combine(string src, string dest) {
            byte[] bytes = FileIO.ReadAllBytes(src);

            using (var stream = new FileStream(dest, FileMode.Append))
            {
                stream.Write(bytes, 0, bytes.Length);
            }

            FileIO.Delete(src);
        }

        #endregion

        #endregion

        #region Edit

        [HttpGet]
        [Authorize(Roles = "admin, moder")]
        public ActionResult EditVideo(int? id) {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Video video = RepManager.Videos.GetById(id.Value);

            if (video == null || !FileIO.Exists(video.Path))
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            #region Thumbnails

            var previews = new List<string>();

            var defPreviewsCount = int.Parse(WebConfigurationManager.AppSettings["ffmpeg:PreviewsCount"]);
            var ffmpegTemp = Server.MapPath(WebConfigurationManager.AppSettings["ffmpeg:WorkingPath"]);

            TimeSpan duration;

            using (var ffmpegWorker = FFMpegWorker.Create(ffmpegTemp))
            {
                IEnumerable<VideoThumbnail> thumbnails = ffmpegWorker.GetThumbnails(video.Path, defPreviewsCount);

                duration = ffmpegWorker.GetVideoInfo(video.Path).Duration;

                foreach (VideoThumbnail thumbnail in thumbnails)
                    previews.Add(ImageHelper.GetImageFromFileAsBase64(thumbnail.PathToFile));
            }

            #endregion

            IEnumerable<SelectListItem> cats = GetVideoCatsAsSelectList(video.CategoryId),
                                        users = UsersAsSelectList(video.LectorId);

            VideoEditViewModel vm = Mapper.Map<Video, VideoEditViewModel>(video);

            #region Filling Viewbag

            ViewBag.VideoCats = cats;

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/Video/Index.cshtml
@{
    ViewBag.Title = "Каталог видео";
}

<hr />
<p>
    <a href="@Url.Action("Upload")" class="btn btn-danger"> Загрузить видео</a>
</p>
<h4>Видео:</h4>
      <hr />
<div class="container-fluid" id="videos-table">

</div>


@section scripts{
    <script type="text/javascript">
        $(function () {
            $(document).ready(function () {
                $('#videos-table').html('<img src="../Content/gifs/loading01.gif" class="gif-loading" title="Загружаем.." alt="Loading" />');

                $.ajax({
                    url: '@Url.Action("Videos")',
                    type: 'GET',
                    cache: false,
                    success: function (result) {
                        $('#videos-table').html(result);
                    },
                    error: function (request, status, error) {
                        console.log(error)
                        $.growl.error({ title: 'Ошибка', message: (error || status) });
                        $('#videos-table').html('');
                    }
                });
            });
        });
    </script>
}

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/Video/UploadVideo.cshtml
@{
    ViewBag.Title = "Загрузка видео";
}
<hr />

<div class="form-horizontal" id="main">
    <div id="loader">
        <input type="file" id="file-upload" alt="upload file" accept=".mp4" />
        <br /><br />
        <button class="btn btn-danger disabled" style="width: 150px;" id="btn-upload">
            Начать загрузку
        </button>
    </div>
    <div hidden id="loading-bar">
        <h3 style="font-family: monospace;">В данный момент ваше видео загружается. Пока что у нас нету информ. панели о статусе загрузки (скорость, процент загрузки, примерное время ожидания), поэтому вы пока можете посмотреть на собакена :3</h3>
        <img src="~/Content/gifs/loading02.gif" class="gif-loading" title="Вжух!" alt="sobaken" />
    </div>
</div>

<script type="text/javascript">
    $(function () {
            var file,
                filename;

            var userName = '@ViewBag.UserName',
                hash = '@ViewBag.Hash';

            var declaredChunkSize = @ViewBag.ChunkSize,
                chunkSize = declaredChunkSize * 1024 * 1024,
                chunkNumber = 0,
                chunk;

            var partialUploadUrl = '@Url.Action("UploadPartial")',
                uploadCompleteUrl = '@Url.Action("UploadComplete")',
                newFileNameUrl = '@Url.Action("GenerateHashName")',
                cleanUpUrl = '@Url.Action("CleanUp")',
                startEditingUrl = '@Url.Action("EditVideo")';

            $('#file-upload').on('change', function(){
                if ($(this)[0].files.length > 0){
                    file = $(this)[0].files[0];
                    $('#btn-upload').removeClass('disabled');
                }
            });

            $(window).on('unload', function (e) {
                console.log('page unloading. disposing temp dir')  ;
                $.ajax({
                    type: 'POST',
                    url: cleanUpUrl,
                    data: {
                        UserName: userName,
                        Oid: hash,
                    },
                });
            });

            RequestFileName = function(ext){
                $.ajax({
                    type: 'GET',
                    url: newFileNameUrl,
                    async: false,
                    data: {
                        extension : ext,
                    },
                    success: function(response){
                        filename = response.Name;
                        console.log('new name: '+filename);
                    }
                });
            };
            
            start = function(){
                var ext = file.name.substring(file.name.lastIndexOf('.') + 1);
                RequestFileName(ext);

                UploadFile();
            };

            $('#btn-upload').click(function () {
                if (file){
                    $('#loader').slideUp('slow');
                    $('#loading-bar').show('slow');
                    console.log('start uploading');

                    $(window).on('beforeunload', function(){
                        return 'Вы уверены, что хотите покинуть страницу?\nНесохраненные данные будут утеряны.'; // not all browsers supported that text
                    });
                    setTimeout(start, 2 * 1000);
                }
            });

            UploadFile = function () {
                var size = file.size;

                var count = Math.round(size / chunkSize) + 1;

                var start = 0,
                    end = chunkSize;

                //var sendingFailed = false;

                while ((chunkNumber < count) /*&& !sendingFailed */) {

                    chunk = file.slice(start, end);

                    var data = new FormData();

                    data.append('chunk', chunk);
                    data.append('chunkNumber', chunkNumber);
                    data.append('fileName', filename);
                    data.append('userName', userName);
                    data.append('hash', hash);

                    $.ajax({
                        url: partialUploadUrl,
                        type: 'POST',

                        cache: false,
                        contentType: false,
                        processData: false,
                        data: data,

                        success: function(response){
                            //if (!response.Succeeded)  {
                            //    $.growl.warning({title: 'Ошибка', message: response.Error});
                            //    sendingFailed = true;
                            //}
                        },
                    });
                    /*
                   if (sendingFailed) {
                       $.growl.error({title: 'Ошибка', message: 'Произошла ошибка во время загрузки.\nПовторите операцию'});
                       $('#loader').removeClass('hidden');
                       $('#loading-bar').addClass('hidden');
                       console.log('uploading failed');
                       $.ajax({
                           type: 'POST',
                           url: 'Url.Action("RefreshFolder")',
                           data: {
                               UserName: userName,
                               Oid: hash,
                           },
                       });
                       return;
                   }
                    */
                    ++chunkNumber;

                    start = end;
                    end = end + chunkSize;
                }

                UploadComplete(count);
            }

            UploadComplete = function (count) {
                
                $.ajax({
                    url: uploadCompleteUrl,
                    type: 'POST',
                    data: {
                        fileName: filename,
                        chunksCount: count,
                        userName: userName,
                        hash: hash,
                    },
                    success: function (result) {
                        if (result.Success){
                            console.log('combing succeeded');
                            $.growl.notice({title: 'Успешно', message: 'Видео загружено. Идет обработка..'});
                            StartEditingUploadedVideo(result.Id);
                        }
                        else{
                            console.log('combing failed');
                            $.growl.error({title: 'Неудачно', message: 'Во время загрузки видео произошла ошибка'});
                        }
                    },
                    error: function (response, status, error) {
                        $.growl.error({ title: 'Ошибка', message: (error || status) });
                    },
                });
            };

            StartEditingUploadedVideo = function(id){
                $.ajax({
                    url: startEditingUrl,
                    type: 'GET',
                    data: {
                        id: id,
                    },
                    success: function(response){
                        $('#loading-bar').slideUp('slow');
                        $('#main').html(response);
                    }
                });
            };
    });
</script>

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/Video/ViewVideo.cshtml
@using MAS.Work.EmployeeCatalog.ViewModels;
@model VideoWatchViewModel
@{
    ViewBag.Title = Model.Name+": Просмотр";
}

<script src="https://content.jwplatform.com/libraries/waYSwWb3.js"></script>

<div class="container-fluid">
    <p>
        <button class="btn btn-danger btn-sm" onclick="window.location.href = '@Url.Action("Index")';">
            <span class="glyphicon glyphicon glyphicon-arrow-left"></span> Назад
        </button>
    </p>
    <div class="row">
        <div class="col-md-8 col-md-push-2">
            <div id="video">
               
            </div>
            <div id="video-info">
                <input type="hidden" id="hidden-id" value="@Model.Id" />
                <h2>@Model.Name</h2>
                <p> @Model.Description</p>
                <p>
                    <div><span class="label label-primary">@Model.Category</span></div>
                    <div class="pull-right"><b>Лектор</b>: @Model.Lector</div>
                </p>
            </div>
            <br /><br />
            <div id="comments" class="well">

            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(function () {
            var getCommsUrl = '@Url.Action("GetComments", "Comment")',
                path = '@Url.Content(@ViewBag.RelativePath + @Model.FileName)';

                jwplayer("video").setup({
                      file: path,
                 });

            RefreshComments = function(){
                $('#comments').html('<img src="/Content/gifs/loading01.gif" class="gif-loading" title="Загружаем.." alt="Loading" />');
                
                $.ajax({
                 url: getCommsUrl,
                 type: 'GET',
                 data: {
                        id: $('#hidden-id').val(),
                 },
                 success: function (response) {
                     $('#comments').html('').html(response);
                  },
                  error: function (response, status, error) {
                      $.growl.error({ title: 'Ошибка', message: (status || error) });
                  }
                });
            };

            RefreshComments();
        });
    </script>
}

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/Video/_Videos.cshtml
@model PageViewModel<VideoPreviewViewModel>
@using MAS.Work.EmployeeCatalog.ViewModels
@using MAS.Work.EmployeeCatalog.Helpers
<div class="form-horizontal">

    <div class="row">
        @foreach (var item in Model.Objects)
        {
            <div class="col-md-4">
                <div class="video-container">
                    <div class="thumbnail">
                        <img alt="video preview" src="@item.Preview">
                        <div class="caption">
                            <h4>@item.Name</h4>
                            <p>@item.PartOfDecription</p>
                            <p><label class="control-label">Лектор</label>: @item.Lector</p>
                            <div class="video-loading-date">
                                <label class="control-label">Загружено</label>: @item.UploadDate
                            </div>
                            <p>Комментариев: @item.CommentsCount</p>
                        </div>
                    </div>
                    <div class="video-overlay">
                        <div class="video-play">
                            <span class="glyphicon glyphicon-play-circle video-preview-span" title="Перейти к просмотру">
                                <input type="hidden" value="@item.Id" />
                            </span>
                            @if (User.IsInRole("admin") || User.IsInRole("moder"))
                            {
                                <span class="glyphicon glyphicon-pencil video-edit-span" title="Редактировать">
                                    <input type="hidden" value="@item.Id" />
                                </span>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
    <div class="btn-group" id="pages">
        <button class="btn btn-default" href="#" id="prev-page" onclick="step(-1)">«</button>
        @Html.PageLinks(Model.PageInfo, x => Url.Action("Videos", new { page = x }))
        <button class="btn btn-default" href="#" id="next-page" onclick="step(1)">»</button>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        var pageSize = '@Model.PageInfo.PageSize',
            pageNumber = '@Model.PageInfo.PageNumber',
            isFirstPage = '@Model.PageInfo.IsFirstPage',
            isLastPage = '@Model.PageInfo.IsLastPage',
            url = '@Url.Action("Videos")',
            editUrl = '@Url.Action("EditVideo")',
            viewVideoUrl = '@Url.Action("ViewVideo")',
            catId = '@Model.Param';

        $('#cats').val(catId);
        $('#prev-page').prop('disabled', isFirstPage);
        $('#next-page').prop('disabled', isLastPage);


        $('.video-preview-span').click(function () {
            var id = $(this).children('input[type=hidden]').val();
            window.location = viewVideoUrl + '?id=' + id; // ну это уже перебор
        });

        $('.video-edit-span').click(function () {
            var id = $(this).children('input[type=hidden]').val();
            window.location = editUrl + '?id=' + id; // ну это уже перебор
        });

        $('#pages').on('click', 'a', function (e) {
            e.preventDefault();
            getPage(this.href, this.text, $('#cats > option:selected').val());
        });
    });

    function step(itteration) {
        var pageNum = parseInt(pageNumber) + itteration;
        var catId = $('#cats > option:selected').val()
        getPage(url, pageNum, catId);
    }

    function getPage(href, pageNum, catId) {
        $('#videos-table').html('<img src="/content/gifs/loading01.gif" class="gif-loading">');

        $.ajax({
            url: href,
            data: {
                page: pageNum,
                catId: catId,
            },
            type: 'GET',
            cache: false,
            success: function (result) {
                $('#videos-table').html(result);
            },
            error: function (request, status, error) {
                console.log(error)
                $.growl.error({ message: error });
                $('#videos-table').html('');
            }
        });
    }
</script>