EmployeeCatalog/MAS.Work.EmployeeCatalog/Controllers/AdminPanelController.cs
namespace MAS.Work.EmployeeCatalog.Controllers {
    #region References

    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Threading.Tasks;
    using System.Web;
    using System.Web.Mvc;
    using AutoMapper;
    using Ef;
    using Helpers;
    using Models;
    using FileIO = System.IO.File;
    using Validators;
    using Microsoft.AspNet.Identity;
    using Microsoft.AspNet.Identity.EntityFramework;
    using ViewModels;
    using System.Web.Configuration;
    using System.IO;
    #endregion

    [Authorize(Roles = "admin")]
    public class AdminPanelController : BaseController {
        [HttpGet]
        public ActionResult Index() {
            IOrderedEnumerable<ApplicationUser> users = UserManager.Users.ToList().OrderBy(x => x.RegisterDate);
            Logger.Info("{0}: Получение списка пользователей. Найдено {1}.", User.Identity.Name, users.Count());

            return View(users);
        }

        #region User

        #region Create

        [HttpGet]
        public ActionResult UserCreate() {
            IEnumerable<SelectListItem> orgs = GetOrganizationAsSelectList();

            Logger.Info("{0}: Получение списка организаций. Найдено {1}.", User.Identity.Name, orgs.Count());

            IEnumerable<SelectListItem> posts = GetPostsAsSelectList();

            Logger.Info("{0}: Получение списка должностей. Найдено {1}.", User.Identity.Name, posts.Count());

            ViewBag.Orgs = orgs;
            ViewBag.Posts = posts;

            return View();
        }

        [HttpPost]
        [ValidateByAjax]
        public async Task<ActionResult> UserCreate(HttpPostedFileBase originFile, AppUserRegisterViewModel vm, string RolesString) {
            try
            {
                var user = new ApplicationUser();

                Logger.Info("{0}: Попытка создать учетную запись пользователя", User.Identity.Name);

                Mapper.Map<AppUserRegisterViewModel, ApplicationUser>(vm, user);

                Employee emp = Mapper.Map<Employee>(vm);

                var password = System.Web.Security.Membership.GeneratePassword(10, 1) + "1";

                Logger.Info("{0}: Запрос временного пароля для учетной записи", User.Identity.Name);

                IdentityResult result = await UserManager.CreateUser(user, password, emp.ManInfo.Initals);

                Logger.Info("{0}: Создание учетной записи пользователя: успешно", User.Identity.Name);

                if (result.Succeeded)
                {
                    #region empCreating

                    Departament dp = RepManager.Departaments.GetById(vm.DepartamentId.Value);
                    Post post = RepManager.Posts.GetById(vm.PostId.Value);

                    emp.Post = post;
                    emp.Departament = dp;
                    emp.UserId = user.Id;

                    if (originFile != null)
                    {
                        byte[] origin = GetByteFromHttpPostedFile(originFile);

                        emp.ManInfo.Photo = origin;
                        emp.ManInfo.PreviewPhoto = ImageHelper.ConvertBase64ToByte(vm.Preview);
                    }

                    RepManager.Employees.Add(emp);

                    Logger.Info("{0}: Попытка создать записи сотрудника для пользователя", User.Identity.Name);

                    await RepManager.SaveChangesAsync();

                    Logger.Info("{0}: Создание записи сотрудника для пользователя: успешно", User.Identity.Name);
                    #endregion

                    await UserManager.AddToRoleAsync(user.Id, "user");

                    return Json(new { Success = result.Succeeded });
                }
                else
                    return Json(new { Success = result.Succeeded, Errors = result.Errors });
            }
            catch (Exception e)
            {
                Logger.Error(e, "{0}: Неудачная попытка создать учетную запись пользователя", User.Identity.Name);
                return Json(new { Success = false, Errors = new string[] { e.Message } });
            }
        }

        #endregion

        [HttpGet]
        public async Task<ActionResult> Details(string id) {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var user = await UserManager.FindByIdAsync(id);

            var emp = RepManager.Employees.GetByPredicateSingle(e => e.UserId == id);

            if (user == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            var vm = new AppUserInfoViewModel();
            Mapper.Map<ManInfo, AppUserInfoViewModel>(emp.ManInfo, vm);
            Mapper.Map<ApplicationUser, AppUserInfoViewModel>(user, vm);

            return PartialView("_UserDetails", vm);
        }

        [HttpPost]
        public async Task<ActionResult> DeleteUser(string id) {
            if (string.IsNullOrEmpty(id))
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Logger.Info("{0}: Попытка поиска учетной записи с id: {1}", User.Identity.Name, id);

            ApplicationUser user = await UserManager.FindByIdAsync(id);

            if (user == null)
            {
                Logger.Info("{0}: Попытка поиска учетной записи с id: {1}: Неудачно. Пользователь не найден", User.Identity.Name, id);

                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            Logger.Info("{0}: Попытка поиска учетной записи с id: {1}: Успешно. Пользователь найден - ", User.Identity.Name, id,
                user.UserName);

            try
            {
                Logger.Info("{0}: Попытка удалить учетную запись пользователя {1}", User.Identity.Name, user.UserName);

                Employee emp = RepManager.Employees.GetByPredicateSingle(x => x.UserId == id);

                RepManager.ManInfos.Delete(emp.ManInfo);
                RepManager.Employees.Delete(emp);

                await RepManager.SaveChangesAsync();

                IdentityResult result = await UserManager.DeleteUser(user);

                Logger.Info("{0}: Попытка удалить учетную запись пользователя {1}: {2}", User.Identity.Name, user.UserName,
                    result.Succeeded ? "Успешно" : "Неудачно. Причины: " + string.Join("; ", result.Errors));

                return Json(new { Success = result.Succeeded, Errors = result.Errors });
            }
            catch (Exception e)
            {
                Logger.Error(e, "{0}: Неудачная попытка удалить учетную запись пользователя", User.Identity.Name, user.UserName);
                return Json(new { Success = false, Errors = new string[] { e.Message } });
            }
        }

        #region Edit

        [HttpGet]
        public async Task<ActionResult> EditUser(string id) {
            if (string.IsNullOrEmpty(id))
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Logger.Info("{0}: Попытка поиска учетной записи с id: {1}", User.Identity.Name, id);

            ApplicationUser user = await UserManager.FindByIdAsync(id);

            if (user == null)
            {
                Logger.Info("{0}: Попытка поиска учетной записи с id: {1}: Неудачно. Пользователь не найден", User.Identity.Name, id);

                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            Logger.Info("{0}: Попытка поиска учетной записи с id: {1}: Успешно. Пользователь найден - ", User.Identity.Name, id,
                user.UserName);

            Employee emp = RepManager.Employees.GetByPredicateSingle(e => e.UserId == id);

            #region ViewBag with info

            ViewBag.Orgs = GetOrganizationAsSelectList(emp.Departament.Organization.Id);
            ViewBag.Deps = GetDepartamentsAsSelectList(emp.Departament.Id, emp.Departament.Organization.Id);
            ViewBag.Posts = GetPostsAsSelectList(emp.Post.Id);

            ViewBag.PreviewImage = ImageHelper.ConvertByteToBase64(emp.ManInfo.PreviewPhoto ??
                                                                GetDefaultPhotoPreview());

            ViewBag.OriginImage = ImageHelper.ConvertByteToBase64(emp.ManInfo.Photo);

            #endregion

            AppUserEditViewModel vm = Mapper.Map<ApplicationUser, AppUserEditViewModel>(user);
            // TODO: TEST 
            Mapper.Map<Employee, AppUserEditViewModel>(emp, vm);

            return View("_UserEdit", vm);
        }

        [HttpPost]
        public async Task<ActionResult> EditUser(AppUserEditViewModel vm, HttpPostedFileBase originFile) {
            if (string.IsNullOrEmpty(vm.UserId))
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Logger.Info("{0}: Попытка поиска учетной записи с id: {1}", User.Identity.Name, vm.UserId);

            ApplicationUser user = await UserManager.FindByIdAsync(vm.UserId);

            if (user == null)
            {
                Logger.Info("{0}: Попытка поиска учетной записи с id: {1}: Неудачно. Пользователь не найден", User.Identity.Name, vm.UserId);

                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            Logger.Info("{0}: Попытка поиска учетной записи с id: {1}: Успешно. Пользователь найден - ", User.Identity.Name, vm.UserId,
                user.UserName);
            try
            {
                Logger.Info("{0}: Попытка изменения данных учетной записи {2} [id: {1}]", User.Identity.Name, vm.UserId, user.UserName);

                Employee emp = RepManager.Employees.GetByPredicateSingle(e => e.UserId == vm.UserId);

                if (vm.UserName.ToLower() != user.UserName.ToLower())
                {
                    await UserManager.SendEmailAsync(vm.UserId, "Смена логина",
                        MailMessageBodyCreator.CreateForLoginChange(emp.ManInfo.Initals, vm.UserName));
                }

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/AdminPanel/CatalogManage.cshtml
@{
    ViewBag.Title = "Управление каталогом";
}

<p><button class="btn btn-danger" onclick="window.location.href = '@Url.Action("Index", "AdminPanel")';">
    <span class="glyphicon glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Назад</button>
    </p>

<ul class="nav nav-tabs">
    <li role="presentation"><a href="#" id="orgs" onclick="LoadAsync('@Url.Action("ShowOrgs", "AdminPanel")', 1, 10)">Организации</a></li>
    <li role="presentation"><a href="#" onclick="LoadAsync('@Url.Action("ShowDeps", "AdminPanel")', 1, 10)">Отделы</a></li>
    <li role="presentation"><a href="#" onclick="LoadAsync('@Url.Action("ShowPosts", "AdminPanel")', 1, 10)">Должности</a></li>
</ul>
<br />
<div id="table">
</div>

@section scripts{
    <script type="text/javascript">
    $(function(){
        $(".nav li").on("click", function () {
            $(".nav li").removeClass("active");
            $(this).addClass("active");
        });

        LoadAsync = function(adress, page, size){
            $('#table').html('<img src="/content/gifs/loading01.gif" class="gif-loading">');

            $.ajax({
                type: 'GET',
                url: adress,
                data: {
                    page: page,
                    pageSize: size,
                },
                success: function(response){
                    $('#table').html(response);
                },
                error: function(response, status, error){
                    $('#table').html('');
                    $.growl.error({ title: 'Ошибка', message: (error || status), });
                }
            });
        };

        showInModal = function(url, id){
            $.ajax({
                type: 'GET',
                url: url,
                data: { id: id },
                success: function(response){
                    $('#dialogContent').html(result);
                    $('#Dialog').modal('show');
                },
                error: function(response, error, status){
                    $.growl.error({ title: 'Ошибка',  message: (error || status) });
                },
            });
        };

        deleteItem = function(url, itemId, MessageSuccess, callbackUrl){
            var result = confirm('Вы уверены?');
            if (result){
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: { id: itemId },
                    success: function(response){
                        if (response.Success){
                            $.growl.notice({ title: "Успешно", message: MessageSuccess });
                            LoadAsync(callbackUrl)
                        }
                        else
                            $.growl.error({title:'Ошибка', message: result.Error });
                    },
                    error: function(response, status, error){
                        $.growl.error({ title:'Ошибка',  message: (error || status) });
                    },
                });
            }
        };

        $('#orgs').click();

        LoadAsync('@Url.Action("ShowOrgs", "AdminPanel")', 1, 10);
    });
        

    </script>
}

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/AdminPanel/CreateRole.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole

@{
    ViewBag.Title = "Создание роли";
}
@Html.ActionLink("Назад", "RoleManage", null, new { @class = "back-button" })
<br />
@Html.AntiForgeryToken()
@Html.ValidationSummary("", new { @class = "text-danger" })
<div class="form-group">
    <text class="col-md-2 control-label">Название роли</text>
    <div class="col-md-10">
        @Html.TextBoxFor(x => x.Name) <input type="button" class="my-button-2" value="Создать" onclick="submit()" />
    </div>
</div>
<br />
<div class="form-group">
    <h4 class="my-ul-header">Добавить пользователя к роли:</h4>
    <form id="ch">
        <ul class="col-md-10">
            @foreach (MAS.Work.EmployeeCatalog.Models.ApplicationUser user in ViewBag.Users)
            {
                <li>
                    @Html.CheckBox(user.Id) @Html.DisplayFor(x => user.UserName, new { @class = "form-control" })
                </li>
            }
        </ul>
    </form>
</div>


<script type="text/javascript">
    function submit() {
        var form = $('#ch').serialize();
        $.ajax({
            url: '@Url.Action("CreateRole", "AdminPanel")',
            type: 'POST',
            dataType: 'json',
            data:
            {
                RoleName: $('#Name').val(),
                usersString: form
            },
            success: function (data) {
                if (data.Success) {
                    $.growl.notice({title:'Успешно', message: "Роль создана\nВыбранные пользователи добавлены." });
                    window.location.href = '@Url.Action("RoleManage", "AdminPanel")';
                }
                else {
                   for (var i = 0; i < data.Errors.length; i++) {
                         $.growl.error({title:'Ошибка', message: data.Errors[i] });
                    }
                       
                }

            },
            error: function (request, status, error) {
                $.growl.error({title:'Ошибка', message: error });
            }
        });
    };
</script>

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/AdminPanel/Index.cshtml
@model IEnumerable<ApplicationUser>
@using MAS.Work.EmployeeCatalog.Models
@{
    ViewBag.Title = "Админка";
}
<h4>Опции:</h4>

<div class="form-horizontal">

    <ul class="nav nav-pills nav-stacked well well-sm col-md-3">
        <li role="presentation"><a href="@Url.Action("RoleManage")">Управление ролями</a></li>
        <li role="presentation"><a href="@Url.Action("CatalogManage")">Управление каталогом</a></li>
        <li role="presentation"><a href="@Url.Action("VideoCatalog")">Управление видео</a></li>
        <li role="presentation"><a href="@Url.Action("UserCreate")">Создать пользователя</a></li>
        <li role="presentation" class="active"><a href="#">Список пользователей</a></li>
    </ul>
    <br /><br />
    @{ Html.RenderPartial("_UsersTable", Model);}
</div>

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/AdminPanel/RoleManage.cshtml
 @{ ViewBag.Title = "Управление группами"; }

<p>
    <button class="btn btn-danger" onclick="window.location.href = '@Url.Action("Index")';">
    <span class="glyphicon glyphicon glyphicon-arrow-left" aria-hidden="true"></span> Назад</button>
</p>

<p>
    <b>Система ролей</b> - универсальный способ разграничения доступа пользователя к различным ресурсам приложения.
</p>


<div class="btn-toolbar" role="group">
    <button class="btn btn-success btn-sm" id="btn-add-to-role">
        Добавить пользователя в роль
        </button>
    <button class="btn btn-warning btn-sm" id="btn-delete-from-role">
        Удалить пользователя из роли
        </button>
</div>
<br/><br/>
<div id="list">

</div>

<script type="text/javascript">
    $(function () {
        var rolesListUrl = '@Url.Action("GetRoles")',
            roleAddUserUrl = '@Url.Action("AddUserToRole")',
            roleDeleteUser = '@Url.Action("RemoveUserFromRole")';

        RequestRolesList = function () {
            $('#list').html('<img src="../Content/gifs/loading01.gif" class="gif-loading" title="Загружаем.." alt="Loading" />');

            $.ajax({
                type: 'GET',
                url: rolesListUrl,
                success: function (result) {
                    $('#list').html('').html(result);
                },
                error: function (request, status, error) {
                    $.growl.error({ title: 'Ошибка', message: error });
                     $('#list').html('');
                }
            });
        };

        $('#btn-add-to-role').click(function(){
            showInModal(roleAddUserUrl);
        });

        $('#btn-delete-from-role').click(function(){
            showInModal(roleDeleteUser);
        });

        RequestRolesList();
    });

    function showInModal(url, id) {
        $.ajax({
            type: 'GET',
            url: url,
            data: { id: id },
            success: function (result) {
                $('#dialogContent').html(result);
                $('#Dialog').modal('show');
            },
            error: function (request, status, error) {
                $.growl.error({ title: 'Ошибка', message: error });
            }
        })
    }

</script>

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/AdminPanel/_AddUserToRole.cshtml
<div class="modal-content">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        <h4 class="control-label">Добавление в группу</h4>
    </div>
    <div class="modal-body">
        <div class="form-horizontal">

            <div class="form-group">
                <label class="col-md-4 control-label"> Пользователь: </label>
                <div class="col-md-8">
                    @Html.DropDownList("Users", (ViewBag.Users as IEnumerable<SelectListItem>), new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label"> Роль: </label>
                <div class="col-md-8">
                    @Html.DropDownList("Roles", (ViewBag.Roles as IEnumerable<SelectListItem>), new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-4 col-md-4">
                    <input type="button" value="Добавить" class="btn btn-success btn-block" onclick="SendPost()" />
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function SendPost() {
        $.ajax({
            url: '@Url.Action("AddUserToRole")',
            type: 'POST',
            dataType: 'json',
            data: {
                userId: $("#Users > option:selected").val(),
                role: $("#Roles > option:selected").val(),
            },

            success: function (data) {
                if (data.Success) {
                    $.growl.notice({ title: '', message: "Добавление успешно" });
                    $('#Dialog').modal('hide');
                    RequestRolesList();
                }
                else {
                    for (var i = 0; i < data.Errors.length; i++) {
                        $.growl.warning({ title: '', message: data.Errors[i] });
                    }
                }
            },

            error: function (request, status, error) {
                $.growl.error({ message: error, duration: 3 * 1000 });
                for (var i = 0; i < request.responseJSON.length; i++) {
                    $.growl.error({ title: '', message: request.responseJSON[i].errors[0] });
                }
            }
        });
    }

</script>

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/AdminPanel/_DepEdit.cshtml
@model DepartamentViewModel
@using MAS.Work.EmployeeCatalog.ViewModels

<div class="modal-content">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        <h4 class="control-label col-md-offset-1">Редактирование данных отдела</h4>
    </div>
    <div class="modal-body">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } }) @Html.ValidationMessageFor(model
                    => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => Model.OrgName, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownList(".Organization.Id", (IEnumerable
                    <SelectListItem>)ViewBag.Orgs, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-4 col-md-4">
                    <input type="button" value="Изменить" class="btn btn-info btn-block" onclick="SendPost()" />
</div>
</div>
</div>
</div>
</div>

<script type="text/javascript">
    function SendPost() {
        $.ajax({
            url: '@Url.Action("EditDep", "AdminPanel")',
            type: 'POST',
            dataType: 'json',
            data:
            {
                Name: $('#Name').val(),
                Id: '@Model.Id',
                OrganizationId: $("#Organization_Id > option:selected").val()
            },

            success: function (data) {
                if (data.Success) {
                    $.growl.notice({ title: 'Успешно', message: "Отдел изменен" });
                    $('#Dialog').modal('hide');
                    LoadAsync('@Url.Action("ShowDeps", "AdminPanel")')
                }
                else {
                    $.growl.error({ title: 'Ошибка', message: data.Error });
                }
            },

            error: function (request, status, error) {
                $.growl.error({ title: 'Ошибка', message: error, duration: 3 * 1000 });
                for (var i = 0; i < request.responseJSON.length; i++) {
                    $.growl.error({ title: '', message: request.responseJSON[i].errors[0] });
                }
            }
        });
    }
</script>

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/AdminPanel/_OrgCreate.cshtml
@model Organization
@using MAS.Work.EmployeeCatalog.Models

<div class="modal-content">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        <h4 class="control-label col-md-offset-1">Создание организации</h4>
    </div>
    <div class="modal-body">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-5" })
                <div class="col-md-7">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } }) @Html.ValidationMessageFor(model
                    => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-3 col-md-8">
                    <input type="button" value="Создать" class="btn btn-success btn-block" onclick="SendPost()" />
</div>
</div>
</div>
</div>
</div>

<script type="text/javascript">
    function SendPost() {
        $.ajax({
            url: '@Url.Action("CreateOrg", "AdminPanel")',
            type: 'POST',
            dataType: 'json',
            data:
            {
                Name: $('#Name').val(),
            },

            success: function (data) {
                if (data.Success) {
                    $.growl.notice({ title: 'Успешно', message: "Организация добавлена" });
                    $('#Dialog').modal('hide');
                    LoadAsync('@Url.Action("ShowOrgs", "AdminPanel")')
                }
                else {
                    $.growl.error({ title:'Ошибка', message: data.Error });
                }
            },

            error: function (request, status, error) {
                $.growl.error({ title: 'Ошибка', message: error, duration: 3 * 1000 });
                for (var i = 0; i < request.responseJSON.length; i++) {
                    $.growl.error({ title: '', message: request.responseJSON[i].errors[0] });
                }
            }
        });
    }
</script>

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/AdminPanel/_PostEmps.cshtml
@model IEnumerable<Employee>
@using MAS.Work.EmployeeCatalog.Models

<div class="modal-content">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        <p>Представители должности</p>
    </div>
    <div class="modal-body">
        <ul>
            @foreach (var worker in Model)
            {
                <li>
                    <p>
                        @Html.DisplayFor(x => worker.ManInfo.SecondName)
                        @Html.DisplayFor(x => worker.ManInfo.FirstName)
                        @Html.DisplayFor(x => worker.ManInfo.MiddleName)
                        - <b>@Html.DisplayFor(x => worker.Departament.Organization.Name)</b>
                    </p>
                </li>
            }
        </ul>
    </div>
</div>

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/AdminPanel/_RoleCreate.cshtml
@model RoleCreateViewModel
@using MAS.Work.EmployeeCatalog.ViewModels

<div class="modal-content">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        <h4 class="control-label col-md-offset-1">Создание роли</h4>
    </div>
    <div class="modal-body">
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            @* добавить сюда dropdown with multiselect *@

            <div class="form-group">
                <div class="col-md-offset-4 col-md-4">
                    <input type="button" value="Создать" class="btn btn-success btn-block" onclick="CreateRole()" />
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function CreateRole() {
       // var users = new FormData();

        $.ajax({
            url: '@Url.Action("CreateRole")',
            type: 'POST',
            dataType: 'json',
            data:
            {
                Name: $('#Name').val(),
                //Users: users,
            },

            success: function (data) {
                if (data.Success) {
                    $.growl.notice({ title: 'Успешно', message: 'Роль создана' });
                    $('#Dialog').modal('hide');
                   location.reload();
                }
                else {
                    $.growl.error({ title: 'Ошибка', message: data.Error });
                }
            },

            error: function (request, status, error) {
                $.growl.error({title:'Ошибка', message: error, duration: 3 * 1000 });
                for (var i = 0; i < request.responseJSON.length; i++) {
                    $.growl.warning({ title: '', message: request.responseJSON[i].errors[0] });
                }
            }
        });
    }
</script>

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/AdminPanel/_VideoList.cshtml
@model PageViewModel<VideoPreviewViewModel>
@using MAS.Work.EmployeeCatalog.ViewModels 
@using MAS.Work.EmployeeCatalog.Helpers

    <table class="table table-hover table-bordered">
        <tr>
            <th>@Html.DisplayNameFor(model => model.Objects.FirstOrDefault().Preview)</th>
            <th>@Html.DisplayNameFor(model => model.Objects.FirstOrDefault().PartOfDecription)</th>
            <th>@Html.DisplayNameFor(model => model.Objects.FirstOrDefault().Author)</th>
            <th>@Html.DisplayNameFor(model => model.Objects.FirstOrDefault().Rate)</th>
            <th>
                <text>Опции</text>
            </th>
        </tr>

        @foreach (var item in Model.Objects) 
        {
        <tr>
            <td class="col-md-1"> <img class="img-thumbnail" src="@item.Preview" alt="video-preview" /> </td> @* // TODO: Add here jq hover viewer *@
            <td class="col-md-4"> @Html.DisplayFor(x => item.PartOfDecription) </td>
            <td> @Html.DisplayFor(x => item.Author) </td>
            <td> @Html.DisplayFor(x => item.Rate) </td>
            <td>
                <div class="btn-toolbar">
                    <a class="btn btn-sm btn-info" href="@Url.Action("ViewVideo","Video", new { @id = @item.Id })">
                    Просмотр
                </a>
                    <a class="btn btn-sm btn-warning" href="@Url.Action("EditVideo","Video", new { @id = @item.Id })">
                    Редактировать
                </a>
                    <button class="btn btn-sm btn-danger" 
                    onclick="deleteItem('@Url.Action("DeleteVideo", "AdminPanel")', '@item.Id', 'Видео удалено', '@Url.Action("ShowVideos")')">
                        Удалить
                    </button>
                </div>
            </td>
        </tr>
        }

    </table>

    <div class="btn-group" id="pages">
        @Html.PageLinks(Model.PageInfo, x => Url.Action("ShowVideos", new { page = x }))
    </div>

    <script type="text/javascript">
        $('#pages').on('click', 'a', function (e) {
                e.preventDefault();
                
                LoadAsync(this.href, this.text, 10);
        });
    </script>