EmployeeCatalog/MAS.Work.EmployeeCatalog/ViewModels/EmployeeViewModels.cs
namespace MAS.Work.EmployeeCatalog.ViewModels
{
    #region References

    using System;
    using System.ComponentModel.DataAnnotations;

    #endregion

    public class EmployeeViewModel
    {
        public int? Id { get; set; }

        [Required]
        [Display(Name = "Имя")]
        public string FirstName { get; set; }

        [Display(Name = "Отчество")]
        public string MiddleName { get; set; }

        [Display(Name = "Фамилия")]
        [Required]
        public string SecondName { get; set; }

        [DataType(DataType.Date)]
        [Required]
        [Display(Name = "Дата рождения")]
        public DateTime BirthDay { get; set; }

        [Display(Name = "ФИО")]
        public string Initals 
        {
            get
            {
                var md = string.IsNullOrEmpty(MiddleName) ? "" : MiddleName[0] + "."; // fix zis

                return SecondName + " " + FirstName[0] + ". " + md;
            }
        }

        public int? PostId { get; set; }

        public int? DepartamentId { get; set; }

        public string Preview { get; set; }
    }


    public class PostViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Название")]
        public string Name { get; set; }

        [Display(Name = "Сотрудники")]
        public int Count { get; set; }
    }

    public class OrganizationViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Название организации")]
        public string Name { get; set; }
    }

    public class DepartamentViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Название отдела")]
        public string Name { get; set; }

        [Display(Name = "Цели отдела")]
        public string[] Aims { get; set; }

        public int OrganizationId { get; set; }

        [Display(Name = "Организация")]
        public string OrgName { get; set; }
    }
}

EmployeeCatalog/MAS.Work.EmployeeCatalog/Controllers/EmployeesController.cs
namespace MAS.Work.EmployeeCatalog.Controllers
{
    #region References

    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Threading.Tasks;
    using System.Web;
    using System.Web.Configuration;
    using System.Web.Mvc;
    using AutoMapper;
    using MAS.Work.EmployeeCatalog.Helpers;
    using MAS.Work.EmployeeCatalog.Models;
    using MAS.Work.EmployeeCatalog.Validators;
    using Microsoft.AspNet.Identity;
    using ViewModels;

    #endregion

    [Authorize]
    public class EmployeesController : BaseController
    {
        #region Edit

        [Authorize(Roles = "admin, moder")]
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Employee emp = RepManager.Employees.GetById(id.Value);

            if (emp == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            var workOrgId = emp.Departament.Organization.Id;

            #region ViewBag with work info

            ViewBag.Orgs = GetOrganizationAsSelectList(workOrgId);
            //    RepManager.Organizations.GetAll().Select(x => new SelectListItem()
            //{
            //    Text = x.Name,
            //    Value = x.Id.ToString(),
            //    Selected = x.Id == workOrgId
            //});

            ViewBag.Posts = GetPostsAsSelectList(emp.Post.Id);
            //RepManager.Posts.GetAll()
            //.Select(x => new SelectListItem()
            //{
            //    Text = x.Name,
            //    Value = x.Id.ToString(),
            //    Selected = x.Id == emp.Post.Id
            //});

            ViewBag.Deps = GetDepartamentsAsSelectList(emp.Departament.Id, emp.Departament.Organization.Id);
                // RepManager.Departaments.GetByPredicate(x => x.Organization.Id == emp.Departament.Organization.Id)
                //.Select(x => new SelectListItem()
                //{
                //    Text = x.Name,
                //    Value = x.Id.ToString(),
                //    Selected = x.Id == emp.Departament.Id
                //});

            #endregion

            EmployeeViewModel vm = Mapper.Map<EmployeeViewModel>(emp);

            ViewBag.PreviewImage = ImageHelper.ConvertByteToBase64(emp.ManInfo.PreviewPhoto ?? GetDefaultPhotoPreview());

            if (emp.ManInfo.Photo != null)
                ViewBag.OriginImage = GetResizedImageInBase64ForView(emp.ManInfo.Photo);

            Logger.Info("Запрос редактирования сотрудника {0}", emp.ManInfo.Initals);

            return View(vm);
        }

        [Authorize(Roles = "admin, moder")]
        [HttpPost]
        [ValidateByAjax]
        public async Task<JsonResult> Edit(HttpPostedFileBase originFile, EmployeeViewModel vm)
        {
            Employee emp = RepManager.Employees.GetById(vm.Id.Value);

            ManInfo mi = RepManager.ManInfos.GetById(emp.ManInfo.Id);

            Mapper.Map<EmployeeViewModel, ManInfo>(vm, mi);

            Departament newDep = RepManager.Departaments.GetById(vm.DepartamentId.Value);
            Post newPost = RepManager.Posts.GetById(vm.PostId.Value);

            emp.Departament = newDep;
            emp.Post = newPost;

            if (originFile != null)
            {
                byte[] origin = GetByteFromHttpPostedFile(originFile);

                Logger.Info("Изменение фото сотрудника {0}", emp.ManInfo.Initals);

                emp.ManInfo.Photo = origin;
                emp.ManInfo.PreviewPhoto = ImageHelper.ConvertBase64ToByte(vm.Preview);
            }

            else if (!string.IsNullOrEmpty(vm.Preview)){ 
                emp.ManInfo.PreviewPhoto = ImageHelper.ConvertBase64ToByte(vm.Preview);
                Logger.Info("Изменение аватара сотрудника {0}", emp.ManInfo.Initals);
            }

            await RepManager.SaveChangesAsync();

            Logger.Info("Изменение данных сотрудника {0}", emp.ManInfo.Initals);

            return Json(new { Success = true });
        }

        #endregion

        [HttpGet]
        public ActionResult Index()
            => View();

        [HttpGet]
        public ActionResult Details(int? id)
        {
            Employee employee = RepManager.Employees.GetById(id.Value);

            ViewBag.ImageData = ImageHelper.ConvertByteToBase64(employee.ManInfo.PreviewPhoto ?? 
                                                                GetDefaultPhotoPreview());

            return PartialView("_Details", employee);
        }

        [HttpGet]
        public ActionResult ShowEmployees(string page, string pageSize)
        {
            int pageNum = string.IsNullOrEmpty(page) ? 1 : Convert.ToInt32(page);
            int pageSize_ = string.IsNullOrEmpty(pageSize) ? 10 : Convert.ToInt32(pageSize);

            IEnumerable<Employee> emps = RepManager.Employees.GetAll() // TODO: Organize in Rep
                .OrderBy(x => x.Id)
                .Skip((pageNum - 1) * pageSize_)
                .Take(pageSize_);

            var pageInfo = new PageInfo
            {
                PageNumber = pageNum,
                PageSize = pageSize_,
                TotalItems = RepManager.Employees.GetAll().Count()
            };

            var ivm = new PageViewModel<Employee>
            {
                PageInfo = pageInfo,
                Objects = emps
            };

            Logger.Info("{0}: Получение списка сотрудников. Страница {1}\\{2}", User.Identity.Name, pageInfo.PageNumber, pageInfo.TotalPages);

            return PartialView("_PList", ivm);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (!id.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Employee employee = RepManager.Employees.GetById(id.Value);

            if (employee == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            ApplicationUser user = await UserManager.FindByIdAsync(employee.UserId);

            if (user == null)
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            RepManager.ManInfos.Delete(employee.ManInfo);
            RepManager.Employees.Delete(employee);

            await RepManager.SaveChangesAsync();

            IdentityResult res = await UserManager.DeleteAsync(user);

            if (!res.Succeeded)
                return Json(new { Success = false, Erorrs = res.Errors });

            Logger.Info("{0}: Удаление сотрудника {1} [учетка {2}]", User.Identity.Name, employee.ManInfo.Initals, user.UserName);

            return Json(new { Success = true });
        }

        #region Filter

        [HttpGet]
        public ActionResult SearchEmployees()
        {
            ViewBag.Posts = GetPostsAsSelectList(); // TODO: Add logging

            return PartialView("_Search");
        }

        [HttpGet]
        public ActionResult Filter(string name, int? postId, string age, string startDate, string endDate)
        {
            if (!postId.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Post post = RepManager.Posts.GetById(postId.Value);

            DateTime dtStart = string.IsNullOrEmpty(startDate) ? DateTime.MinValue : DateTime.Parse(startDate);
            DateTime dtEnd = string.IsNullOrEmpty(endDate) ? DateTime.MaxValue : DateTime.Parse(endDate);

            IEnumerable<Employee> emps = RepManager.Employees.GetByPredicate(emp =>
           emp.ManInfo.SecondName.ToLower().Contains(name.ToLower()) // А правильно ли это?
                       && emp.ManInfo.BirthDay > dtStart
                       && emp.ManInfo.BirthDay < dtEnd
                       && emp.Post.Id == postId.Value
            );
           
            return PartialView("_EmpList", emps.Where(emp => emp.ManInfo.Age.ToString().Contains(age)));
        }

        #endregion
    }
}

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/Employees/Index.cshtml
@{
    ViewBag.Title = "Каталог сотрудников";
}

<ul class="nav nav-tabs">
    <li role="presentation" id="emps"><a href="#/" onclick="LoadAsync('@Url.Action("ShowEmployees")')"> Список сотрудников</a></li>
    <li role="presentation"><a href="#/" onclick="LoadAsync('@Url.Action("SearchEmployees")')"> Поиск сотрудника </a></li>
</ul>
<br/>
<div id="table">

</div>

@section scripts{
    <script type="text/javascript">
        $('.nav li').on('click', function () {
            $('.nav li').removeClass('active');
            $(this).addClass('active');
        });

        $(document).ready(function () {
            $('#emps').click();
           LoadAsync('@Url.Action("ShowEmployees")')
        });
    </script>
}
<script type="text/javascript">
    function LoadAsync(adress) {
        $('#table').html('<img src="../Content/gifs/loading01.gif" class="gif-loading" title="Загружаем.." alt="Loading" />');
       
        $.ajax({
            type: 'GET',
            url: adress,
            success: function (result) {
                $('#table').html(result);
            },
            error: function (request, status, error) {
                $.growl.error({ message: error });
                $('#table').html('');
            }
        });
    }

    function showInModal(url, id){
        $.ajax({
            type: 'GET',
            url: url,
            data: { id: id },
            success: function (result) {
                    $('#dialogContent').html(result);
                    $('#Dialog').modal('show');
            },
            error: function (request, status, error) {
                $.growl.error({ message: error });
            }
        })
    }

    function deleteItem(url, itemId, MessageSuccess, callbackUrl) {
        var result = confirm('Вы уверены?');
        if (result) {
            $.ajax({
                type: 'POST',
                url: url,
                data: { id: itemId },
                success: function (result) {
                    if (result.Success) {
                        $.growl.warning({ title: 'Удаление', message: MessageSuccess });
                        LoadAsync('@Url.Action("ShowEmployees")');
                    }

                    else
                        $.growl.error({ message: result.Error, title:'Ошибкен' });
                },
                error: function (request, status, error) {
                    $.growl.error({ message: error, title: 'Ошибкен' });
                }
            })
        }
    }
</script>

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/Employees/_Details.cshtml
@model Employee
@using MAS.Work.EmployeeCatalog.Models

<div class="modal-content">
    <div class="modal-body">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="detailsLabel">Данные сотрудника @Model.ManInfo.Initals</h4>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-6">
                    <img src="@ViewBag.ImageData" class="crop-image" />
                </div>
                <div class="col-md-6">
                    <p><label class="control-label">Фамилия</label>: @Model.ManInfo.SecondName</p>
                    <p><label class="control-label">Имя</label>: @Model.ManInfo.FirstName</p>
                    <p><label class="control-label">Отчество</label>: @Model.ManInfo.MiddleName</p>
                    <p><label class="control-label">Дата рождения</label>: @Model.ManInfo.BirthDay.ToString("dd.MM.yyyy") <i>(Возраст: @Model.ManInfo.Age)</i></p>
                    <hr align="left" />
                    <h3>Место работы</h3>
                    <p><label class="control-label">Организация</label>: @Model.Departament.Organization.Name</p>
                    <p><label class="control-label">Отдел</label>: @Model.Departament.Name</p>
                    <p><label class="control-label">Должность</label>: @Model.Post.Name</p>
                </div>
            </div>
        </div>
        
    </div>
</div>

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/Employees/_EmpList.cshtml
@model IEnumerable<Employee>
@using MAS.Work.EmployeeCatalog.Models

<table class="table table-hover table-bordered table-condensed">
    <tr>
        <th>@Html.DisplayNameFor(model => model.ManInfo.Initals)</th>
        <th>@Html.DisplayNameFor(model => model.Post)</th>
        <th>@Html.DisplayNameFor(model => model.Departament)</th>
        <th>Опции</th>
    </tr>

    @foreach (var item in Model)
            {
        <tr>
            <th>@Html.DisplayFor(x => item.ManInfo.Initals)</th>
            <th>@Html.DisplayFor(x => item.Post.Name)</th>
            <th>@Html.DisplayFor(x => item.Departament.Name)</th>
            <td>
                @if (User.IsInRole("admin") || User.IsInRole("moder"))
                {
                    <a href="@Url.Action("Edit", new { @id = item.Id})" class="btn btn-xs btn-warning">Редактировать</a>
                }
                <a href="#/" onclick="showInModal('@Url.Action("Details")','@item.Id')" class="btn btn-xs btn-info">Полные данные</a>
                @if (User.IsInRole("admin"))
                {
                    <a href="#/" onclick="deleteItem('@Url.Action("Delete")', '@item.Id', 'Сотрудник удален', '')" class="btn btn-xs btn-danger">Удалить</a>
                }
            </td>
        </tr>
    }
</table>

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/Employees/_PList.cshtml
@model PageViewModel<Employee>
@using MAS.Work.EmployeeCatalog.ViewModels
@using MAS.Work.EmployeeCatalog.Helpers
@using MAS.Work.EmployeeCatalog.Models

@{
ViewBag.Title = "Список сотрудников: " + Model.PageInfo.PageNumber + " из " + Model.PageInfo.TotalPages + ".";
}

<div class="form-horizontal">

    <div id="page-size-block" class="row">
        <div class="col-md-2"> Количество записей на странице</div>
        <div class="col-md-2">
            <select style="width:75px;" class="form-control" id="pageSizeSelector">
                <option>5</option>
                <option>10</option>
                <option>25</option>
                <option>50</option>
                <option>100</option>
            </select>
        </div>
    </div>
    <br />
    <div id="table">

        <table class="table table-hover table-bordered table-condensed">
            <tr>
                <th>@Html.DisplayNameFor(model => model.Objects.FirstOrDefault().ManInfo.Initals)</th>
                <th>@Html.DisplayNameFor(model => model.Objects.FirstOrDefault().Post)</th>
                <th>@Html.DisplayNameFor(model => model.Objects.FirstOrDefault().Departament)</th>
                <th>Опции</th>
            </tr>

            @foreach (var item in Model.Objects)
        {
        <tr>
            <th>@Html.DisplayFor(x => item.ManInfo.Initals)</th>
            <th>@Html.DisplayFor(x => item.Post.Name)</th>
            <th>@Html.DisplayFor(x => item.Departament.Name)</th>
            <td>
                @if (User.IsInRole("admin") || User.IsInRole("moder"))
                    {
                    <a href="@Url.Action("Edit", new { @id = item.Id})" class="btn btn-xs btn-warning">Редактировать</a>
                    }
                <a href="#/" onclick="showInModal('@Url.Action("Details")','@item.Id')" class="btn btn-xs btn-info">Полные данные</a>
                @if (User.IsInRole("admin"))
                    {
                    <a href="#/" onclick="deleteItem('@Url.Action("Delete")', '@item.Id', 'Сотрудник удален', '')" class="btn btn-xs btn-danger">Удалить</a>
                    }
            </td>
        </tr>
        }

        </table>
    </div>
</div>

<br />

<div class="btn-group" id="pages">
        <button class="btn btn-default" href="#" id="prev-page" onclick="step(-1)">«</button>
            @Html.PageLinks(Model.PageInfo, x => Url.Action("ShowEmployees", new { page = x }))
        <button class="btn btn-default" href="#" id="next-page" onclick="step(1)">»</button>
    </div>

<script type="text/javascript">
        $(function () {
            $(document).ready(function () {
                $('#pageSizeSelector').val('@Model.PageInfo.PageSize');

                $('#prev-page').prop('disabled', '@Model.PageInfo.IsFirstPage');

                $('#next-page').prop('disabled', '@Model.PageInfo.IsLastPage')
            })
        });

        $('#pages').on('click', 'a', function (e) {
            e.preventDefault();
            getPage(this.href, this.text, $('#pageSizeSelector > option:selected').val());
        });

        $('#pageSizeSelector').change(function () {
            var url = '@Url.Action("ShowEmployees", "Employees")';
            var pageNumber = '@Model.PageInfo.PageNumber';
            var pageSize = $('#pageSizeSelector > option:selected').val();

            getPage(url, pageNumber, pageSize);
        });

        function step(itteration) {
            var url = '@Url.Action("ShowEmployees")';
            var pageNumber = '@Model.PageInfo.PageNumber+itteration';
            var pageSize = $('#pageSizeSelector > option:selected').val();
            getPage(url, pageNumber, pageSize);
        }

        function getPage(href, text, pageSize) {
            $('#table').html('<img src="/content/gifs/loading01.gif" class="gif-loading">');

            $.ajax({
                url: href,
                data: {
                    page: text,
                    pageSize: pageSize
                },
                type: 'GET',
                cache: false,
                success: function (result) {
                    $('#table').html(result);
                },
                error: function (request, status, error) {
                    console.log(error)
                    $.growl.error({ message: error });
                    $('#table').html('');
                }
            });
        }
    </script>

EmployeeCatalog/MAS.Work.EmployeeCatalog/Views/Employees/_Search.cshtml
<h3>Поиск сотрудника</h3>
<br />
<div class="form-horizontal">

    <div class="form-group">
        <label class="control-label col-md-2">Поиск по Фамилии</label>
        <div class="col-md-10">
            <input type="text" class="form-control" id="SecondName" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Поиск по Должности</label>
        <div class="col-md-10">
            @Html.DropDownList("Post", (ViewBag.Posts as IEnumerable<SelectListItem>), new { @class = "form-control", id = "postlist" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Поиск по Возрасту</label>
        <div class="col-md-10">
            <input type="text" class="form-control" id="Age" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Поиск по дате рождения</label>
        <div class="col-md-9">
            <input type="text" class="form-control col-md-1" id="dates" placeholder="Выберите границы">
        </div>
    </div>
</div>

<input type="button" class="btn btn-info col-md-offset-2 btn-block" id="btfilter" value="Поиск" />
<br /><hr /><br />
<div id="results">

</div>

<script type="text/javascript">
    $(function () {
        $.ajaxSetup({ cache: false });
        $('#dates').on('keydown', function (e) {
            $('#dates').val() = "";
        })

        $('#btfilter').click(function (e) {
            e.preventDefault();
            $('#results').html('<img src="/content/gifs/loading01.gif" class="gif-loading">');

            var datesArray = $('#dates').val().split(", ");
            var maxDate, minDate;

            if (datesArray.length > 1) {

                // pzdc govnocod
                var dates = [];
                var temp_min = new Date("01.01.2900");
                var temp_max = new Date(1);

                var max, min;

                datesArray.forEach(function (item, i) {
                    var from = item.split(".");
                    var date = new Date(from[2], from[1] - 1, from[0]);

                    if (temp_max < date) {
                        temp_max = date;
                        max = item;
                    }

                    if (temp_min > date) {
                        temp_min = date;
                        min = item;
                    }
                    dates.push(date);
                });

                minDate = min;
                maxDate = max;
            }

            $.ajax({
                type: 'GET',
                url: '@Url.Action("Filter")',
                data: {
                    name: $('#SecondName').val(),
                    postId: $('#postlist > option:selected').val(),
                    age: $('#Age').val(),
                    startDate: minDate,
                    endDate: maxDate
                },
                success: function (result) {
                    $.growl.notice({ tittle: "Поиск", message: "Поиск завершен" })
                    $('#results').html(result);
                },
                error: function (request, status, error) {
                    $.growl.error({ tittle: "Ошибка", message: error })
                    $('#results').html('');
                }
            })
        });

        $(document).ready(function () {
            $('#dates').datepicker({
                startDate: "01.01.1900",
                endDate: "31.12.2010",
                startView: 1,
                multidate: true,
                multidateSeparator: ", ",
                language: "ru",
                format: "dd.mm.yyyy",
                orientation: "auto right",
                keyboardNavigation: false,
            });
        });
    });
</script>